### ISSUE TITLE
Add sample config file

### ISSUE THREAD

**Issue by laldoroty** [Roman-Supernova-PIT/phrosty#80]
for example, mine has this, and I don't think anyone else's has keep_intermediate right now:
```
ou24psf:
  config_file: /sn_info_dir/tds.yaml

photometry:
  phrosty:

    image_type: ou2024fits
    force_sky_subtract: true
    keep_intermediate: true

    paths:
      temp_dir: /phrosty_temp
      sn_info_dir: /sn_info_dir
      dia_out_dir: /dia_out_dir
      image_base_dir: /sims_dir
      snana_pq_dir: /snana_pq_dir
      snid_lc_dir: /snid_lc_dir
      ltcv_dir: /lc_out_dir

    psf:
      type: ou24PSF
```
